export class Accounts {
  constructor(
    public id: number,
    public budgetYear: number,
    public officeName: string,
    public fundId: number,
    public classificationId: number,
    public classificationCode: string,
    public subclassificationId: number,
    public subclassificationCode: string,
    public code: string,
    public description: string,
    public amount: number,
    public classification: string,
    public subclassification: string,
    public classorder: number,
    public subclassorder: number,
    public type: number,
    public officeCode: string,
    public batch: string,
    public officeId: string,
    public project: string,
    public isContinuing: number,
    public ordering: number,
    public created_at: Date,
    public updated_at: Date,
    public deleted_at: Date,
  ) {
    return {
      id,
      budgetYear,
      officeName,
      fundId,
      classificationId,
      classificationCode,
      subclassificationId,
      subclassificationCode,
      code,
      description,
      amount,
      classification,
      subclassification,
      classorder,
      subclassorder,
      type,
      officeCode,
      batch,
      officeId,
      project,
      isContinuing,
      ordering,
      created_at,
      updated_at,
      deleted_at,
    }
  }
}