export class AppItemModel {
  constructor(
    public id: number,
    public no: number,
    public budgetYear: number,
    public appropriationId: number,
    public appropriationName: string,
    public office: string,
    public className: string,
    public itemId: string,
    public itemName: string,
    public groupDescription: string,
    public groupId: string,
    public typeId: string,
    public typeDescription: string,
    public specification: string,
    public uom: string,
    public qty: number,
    public price: number,
    public total: number,
    public mop: string,
    public project: string,
    public first_qtr_qty: number,
    public first_qtr_amt: number,
    public second_qtr_qty: number,
    public second_qtr_amt: number,
    public third_qtr_qty: number,
    public third_qtr_amt: number,
    public fourth_qtr_qty: number,
    public fourth_qtr_amt: number,
    public isApproved: boolean,
    public IsLocked: boolean,
    public locked_note: string,
    public pr_qty: number,
    public pr_qty_balance: number,
    public pr_total: number,
    public pr_balance: number,
  ) {
    return {
      id,
      no,
      budgetYear,
      appropriationId,
      appropriationName,
      office,
      className,
      itemId,
      itemName,
      groupDescription,
      groupId,
      typeId,
      typeDescription,
      specification,
      uom,
      qty,
      price,
      total,
      mop,
      project,
      first_qtr_qty,
      first_qtr_amt,
      second_qtr_qty,
      second_qtr_amt,
      third_qtr_qty,
      third_qtr_amt,
      fourth_qtr_qty,
      fourth_qtr_amt,
      isApproved,
      IsLocked,
      locked_note,
      pr_qty,
      pr_qty_balance,
      pr_total,
      pr_balance
    }
  }
}