// ignore_for_file: unnecessary_new, prefer_collection_literals

export class TransactionModel {
  constructor(
    public id: string,
    public rfqId: string,
    public rfqNo: string,
    public transactionNo: string,
    public transactionDate: Date,
    public supplyDescription: string,
    public remarks: string,
    public status: string,
    public dateSaved: Date,
    public dateUpdated: Date,
    public recommendingDate: Date,
    public prId: string,
    public prNo: string,
    public prDate: Date,
    public departmentId: string,
    public departmentName: string,
    public openningDate: Date,
    public location: string,
    public canvasserId: string,
    public canvasserName: string,
    public procurementMode: string,
    public biddingType: string,
    public approvedBudget: number,
    public bidSecurity: number,
    public bidDocsFee: number,
    public prType: string,
    public title: string,
    public sectionId: number,
    public sectionName: string,
    public alobsNo: string,
    public alobsDate: Date,
    public saiNo: string,
    public saiDate: Date,
    public ppNo: string,
    public sourceOfFund: string,
    public rationale: string,
    public ppId: string,
    public referenceNo: string,
    public referenceDate: Date,
    public projectTitle: string,
    public projectLocation: string,
    public projLocBarangay: string,
    public description: string,
    public projectStartDate: Date,
    public projectDuration: string,
    public projectType: string,
    public projectCost: number
  ) {
    return {
      id,
      rfqId,
      rfqNo,
      transactionNo,
      transactionDate,
      supplyDescription,
      remarks,
      status,
      dateSaved,
      dateUpdated,
      recommendingDate,
      prId,
      prNo,
      prDate,
      departmentId,
      departmentName,
      openningDate,
      location,
      canvasserId,
      canvasserName,
      procurementMode,
      biddingType,
      approvedBudget,
      bidSecurity,
      bidDocsFee,
      prType,
      title,
      sectionId,
      sectionName,
      alobsNo,
      alobsDate,
      saiNo,
      saiDate,
      ppNo,
      sourceOfFund,
      rationale,
      ppId,
      referenceNo,
      referenceDate,
      projectTitle,
      projectLocation,
      projLocBarangay,
      description,
      projectStartDate,
      projectDuration,
      projectType,
      projectCost,
    }
  }
}